### ISSUE TITLE
Host not found

### ISSUE THREAD

**Issue by sayoojbkumar** [taviso/rbndr#7]
i was trying to this tool every time it responded with **Host 0c0b3a59.7f000001.rbndr.us not found: 3(NXDOMAIN)**

**Comment by taviso** [comment]
It works fine here, what tool are you using?

```
$ host 0c0b3a59.7f000001.rbndr.us
0c0b3a59.7f000001.rbndr.us has address 127.0.0.1
$ host 0c0b3a59.7f000001.rbndr.us
0c0b3a59.7f000001.rbndr.us has address 12.11.58.89
```

**Comment by sayoojbkumar** [comment]
Tool 🤔 I was using the site that mentioned in git 
https://lock.cmpxchg8b.com/rebinder.html

Sorry it was my mistake it works fine thanks 😊
